### ISSUE TITLE
Anomalies in treatment

### ISSUE THREAD

**Issue by wlynn00** [dongtsi/OWAD#3]
May I ask what happens if there are abnormal samples in the new treatment set and the abnormal detector classifies them as normal?

**Comment by dongtsi** [comment]
This belongs to the shift of **abnormality** (new anomalies appear in the new set).
As claimed in the paper, OWAD mainly focuses on the shift of normality because the anomaly detection model cannot be aware of abnormality during learning. However, if we correctly handle the normality shift, the abnormality shift can ideally also be handled as the abnormality is the opposite of normality. So you could try to handle normality shift first and see the results.
If it doesn't work, maybe you should try other techniques, like [unlearning](https://dl.acm.org/doi/abs/10.1145/3319535.3363226).

**Comment by wlynn00** [comment]
So is it not allowed to have abnormal samples in the treatment set？
If not, how does OWAD handle real abnormal samples？

**Comment by dongtsi** [comment]
No, treatment set could include anomalies, that's why we involve a step of labeling to filter anomalies. 
See the motivation example in the paper: 
> As shown in Fig. 2, we keep the samples with high weights, including xc1, xc2, xc4 and xt4, xt5. xt4, xt5 are manually labeled and filter out anomalies (i.e., not included for the following step, no one is filtered in this example)

**Comment by wlynn00** [comment]
> No, treatment set could include anomalies, that's why we involve a step of labeling to filter anomalies. See the motivation example in the paper:
> 
> > As shown in Fig. 2, we keep the samples with high weights, including xc1, xc2, xc4 and xt4, xt5. xt4, xt5 are manually labeled and filter out anomalies (i.e., not included for the following step, no one is filtered in this example)

I understand. Thanks! A very inspiring study!
